#ifndef DEFINES_H
#define DEFINES_H

#define PB3_ON							GPIOB->BSRR = GPIO_BSRR_BS_3
#define PB3_OFF							GPIOB->BSRR = GPIO_BSRR_BR_3
#define PB4_ON							GPIOB->BSRR = GPIO_BSRR_BS_4
#define PB4_OFF							GPIOB->BSRR = GPIO_BSRR_BR_4


#define HOURS_A_LOW					GPIOB->BSRR = GPIO_BSRR_BR_6
#define HOURS_A_HIGH				GPIOB->BSRR = GPIO_BSRR_BS_6
#define HOURS_B_LOW					GPIOB->BSRR = GPIO_BSRR_BR_5
#define HOURS_B_HIGH				GPIOB->BSRR = GPIO_BSRR_BS_5

#define HOURS_LED01_LOW			GPIOA->BSRR = GPIO_BSRR_BR_15
#define HOURS_LED01_HIGH		GPIOA->BSRR = GPIO_BSRR_BS_15
#define HOURS_LED23_LOW			GPIOA->BSRR = GPIO_BSRR_BR_12
#define HOURS_LED23_HIGH		GPIOA->BSRR = GPIO_BSRR_BS_12
#define HOURS_LED45_LOW			GPIOA->BSRR = GPIO_BSRR_BR_9
#define HOURS_LED45_HIGH		GPIOA->BSRR = GPIO_BSRR_BS_9
#define HOURS_LED67_LOW			GPIOA->BSRR = GPIO_BSRR_BR_10
#define HOURS_LED67_HIGH		GPIOA->BSRR = GPIO_BSRR_BS_10
#define HOURS_LED89_LOW			GPIOA->BSRR = GPIO_BSRR_BR_11
#define HOURS_LED89_HIGH		GPIOA->BSRR = GPIO_BSRR_BS_11
#define HOURS_LEDAB_LOW			GPIOB->BSRR = GPIO_BSRR_BR_7
#define HOURS_LEDAB_HIGH		GPIOB->BSRR = GPIO_BSRR_BS_7

#define HOURS_LED_ALL_HIGH	GPIOA->BSRR = (GPIO_BSRR_BS_15 | GPIO_BSRR_BS_12 | GPIO_BSRR_BS_9 | GPIO_BSRR_BS_10 | GPIO_BSRR_BS_11); GPIOB->BSRR = GPIO_BSRR_BS_7
#define HOURS_LED_ALL_LOW		GPIOA->BSRR = (GPIO_BSRR_BR_15 | GPIO_BSRR_BR_12 | GPIO_BSRR_BR_9 | GPIO_BSRR_BR_10 | GPIO_BSRR_BR_11); GPIOB->BSRR = GPIO_BSRR_BR_7


#define CPLX0_OUTPUT_HIGH		GPIOA->MODER |= GPIO_MODER_MODER4_0; GPIOA->BSRR = GPIO_BSRR_BS_4
#define CPLX0_OUTPUT_LOW		GPIOA->MODER |= GPIO_MODER_MODER4_0; GPIOA->BSRR = GPIO_BSRR_BR_4
#define CPLXO_INPUT					GPIOA->MODER &=~GPIO_MODER_MODER4_0

#define CPLX1_OUTPUT_HIGH		GPIOA->MODER |= GPIO_MODER_MODER5_0; GPIOA->BSRR = GPIO_BSRR_BS_5
#define CPLX1_OUTPUT_LOW		GPIOA->MODER |= GPIO_MODER_MODER5_0; GPIOA->BSRR = GPIO_BSRR_BR_5
#define CPLX1_INPUT					GPIOA->MODER &=~GPIO_MODER_MODER5_0

#define CPLX2_OUTPUT_HIGH		GPIOA->MODER |= GPIO_MODER_MODER6_0; GPIOA->BSRR = GPIO_BSRR_BS_6
#define CPLX2_OUTPUT_LOW		GPIOA->MODER |= GPIO_MODER_MODER6_0; GPIOA->BSRR = GPIO_BSRR_BR_6
#define CPLX2_INPUT					GPIOA->MODER &=~GPIO_MODER_MODER6_0

#define CPLX3_OUTPUT_HIGH		GPIOA->MODER |= GPIO_MODER_MODER7_0; GPIOA->BSRR = GPIO_BSRR_BS_7
#define CPLX3_OUTPUT_LOW		GPIOA->MODER |= GPIO_MODER_MODER7_0; GPIOA->BSRR = GPIO_BSRR_BR_7
#define CPLX3_INPUT					GPIOA->MODER &=~GPIO_MODER_MODER7_0

#define CPLX4_OUTPUT_HIGH		GPIOB->MODER |= GPIO_MODER_MODER0_0; GPIOB->BSRR = GPIO_BSRR_BS_0
#define CPLX4_OUTPUT_LOW		GPIOB->MODER |= GPIO_MODER_MODER0_0; GPIOB->BSRR = GPIO_BSRR_BR_0
#define CPLX4_INPUT					GPIOB->MODER &=~GPIO_MODER_MODER0_0

#define CPLX5_OUTPUT_HIGH		GPIOB->MODER |= GPIO_MODER_MODER1_0; GPIOB->BSRR = GPIO_BSRR_BS_1
#define CPLX5_OUTPUT_LOW		GPIOB->MODER |= GPIO_MODER_MODER1_0; GPIOB->BSRR = GPIO_BSRR_BR_1
#define CPLX5_INPUT					GPIOB->MODER &=~GPIO_MODER_MODER1_0

#define CPLX6_OUTPUT_HIGH		GPIOA->MODER |= GPIO_MODER_MODER1_0; GPIOA->BSRR = GPIO_BSRR_BS_1
#define CPLX6_OUTPUT_LOW		GPIOA->MODER |= GPIO_MODER_MODER1_0; GPIOA->BSRR = GPIO_BSRR_BR_1
#define CPLX6_INPUT					GPIOA->MODER &=~GPIO_MODER_MODER1_0

#define CPLX7_OUTPUT_HIGH		GPIOA->MODER |= GPIO_MODER_MODER8_0; GPIOA->BSRR = GPIO_BSRR_BS_8
#define CPLX7_OUTPUT_LOW		GPIOA->MODER |= GPIO_MODER_MODER8_0; GPIOA->BSRR = GPIO_BSRR_BR_8
#define CPLX7_INPUT					GPIOA->MODER &=~GPIO_MODER_MODER8_0

#define CPLX_ALL_INPUTS			GPIOA->MODER &=~(GPIO_MODER_MODER1_0 | GPIO_MODER_MODER4_0 | GPIO_MODER_MODER5_0 | GPIO_MODER_MODER6_0 | GPIO_MODER_MODER7_0 | GPIO_MODER_MODER8_0); GPIOB->MODER &=~( GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0)

#endif
